CREATE PROCEDURE [dbo].[spReport_Upsert]
	@Id INT = NULL,
    @IsArchive BIT,
    @StartDate DATETIME,
    @EndDate DATETIME,
    @VehicleId INT,
    @UserId INT,
    @AppointmentId INT,
    @CustomerId INT,
    @Date DATETIME,
    @Odometer INT,
    @RoadTestComments NVARCHAR(MAX),
    @GeneralComments NVARCHAR(MAX),
    @StoredFaultCodes NVARCHAR(MAX),
    @AirConditioning NVARCHAR(MAX),
    @Optics NVARCHAR(50),
    @Lights NVARCHAR(MAX),
    @LightsComments NVARCHAR(MAX),
    @FrontWiper NVARCHAR(50),
    @BackWiper NVARCHAR(50),
    @Battery NVARCHAR(50),
    @BatteryComments NVARCHAR(50),
    @RHFTyre NVARCHAR(50),
    @LHFTyre NVARCHAR(50),
    @RHRTyre NVARCHAR(50),
    @LHRTyre NVARCHAR(50),
    @TyresComments NVARCHAR(MAX),
    @IsNeedAlignment BIT,
    @AirFilter NVARCHAR(50),
    @CabinFilter NVARCHAR(50),
    @DriveBelts NVARCHAR(50),
    @TimingBelts NVARCHAR(50),
    @Radiator NVARCHAR(50),
    @Hoses NVARCHAR(50),
    @HosesComment NVARCHAR(MAX),
    @EngineOil NVARCHAR(50),
    @Coolant NVARCHAR(50),
    @BrakeFluid NVARCHAR(50),
    @PowerSteeringFluid NVARCHAR(50),
    @TransmissionFluid NVARCHAR(50),
    @WindScreenWasherFluid NVARCHAR(50),
    @FluidComments NVARCHAR(MAX),
    @SparkPlugs NVARCHAR(50),
    @FuelFilter NVARCHAR(50),
    @FrontSuspension NVARCHAR(50),
    @FrontSuspensionComments NVARCHAR(MAX),
    @RearSuspension NVARCHAR(50),
    @RearSuspensionComments NVARCHAR(MAX),
    @FrontBrakes NVARCHAR(50),
    @FrontBrakesComments NVARCHAR(MAX),
    @RearBrakes NVARCHAR(50),
    @RearBrakesComments NVARCHAR(MAX),
    @Exhaust NVARCHAR(50),
    @ExhaustComments NVARCHAR(MAX),
    @OilLeaks NVARCHAR(50),
    @OilLeaksComments NVARCHAR(MAX),
    @CoolantLeaks NVARCHAR(50),
    @CoolantLeaksComments NVARCHAR(MAX),
    @Other NVARCHAR(MAX),
    @OtherInspectionComments NVARCHAR(MAX)
AS
BEGIN
     IF NOT EXISTS (SELECT * FROM [Report] WHERE Id = @Id)
            BEGIN
                INSERT INTO Report (
            IsArchive,
            StartDate,
            EndDate,
            VehicleId,
            UserId,
            AppointmentId, 
            CustomerId,
            Date,
            Odometer,
            RoadTestComments,
            GeneralComments,
            StoredFaultCodes,
            AirConditioning,
            Optics,
            Lights, 
            LightsComments,
            FrontWiper,
            BackWiper,
            Battery,
            BatteryComments,
            RHFTyre,
            LHFTyre,
            RHRTyre,
            LHRTyre,
            TyresComments,
            IsNeedAlignment,
            AirFilter,
            CabinFilter,
            DriveBelts,
            TimingBelts,
            Radiator, 
            Hoses,
            HosesComment,
            EngineOil,
            Coolant,
            BrakeFluid,
            PowerSteeringFluid,
            TransmissionFluid,
            WindScreenWasherFluid,
            FluidComments,
            SparkPlugs,
            FuelFilter,
            FrontSuspension,
            FrontSuspensionComments,
            RearSuspension, 
            RearSuspensionComments,
            FrontBrakes,
            FrontBrakesComments,
            RearBrakes,
            RearBrakesComments,
            Exhaust,
            ExhaustComments,
            OilLeaks,
            OilLeaksComments,
            CoolantLeaks,
            CoolantLeaksComments,
            Other,
            OtherInspectionComments
        ) VALUES (
            @IsArchive,
            @StartDate,
            @EndDate,
            @VehicleId,
            @UserId,
            @AppointmentId, 
            @CustomerId,
            @Date,
            @Odometer,
            @RoadTestComments,
            @GeneralComments,
            @StoredFaultCodes,
            @AirConditioning,
            @Optics,
            @Lights, 
            @LightsComments,
            @FrontWiper,
            @BackWiper,
            @Battery,
            @BatteryComments,
            @RHFTyre,
            @LHFTyre,
            @RHRTyre,
            @LHRTyre,
            @TyresComments,
            @IsNeedAlignment,
            @AirFilter,
            @CabinFilter,
            @DriveBelts,
            @TimingBelts,
            @Radiator, 
            @Hoses,
            @HosesComment,
            @EngineOil,
            @Coolant,
            @BrakeFluid,
            @PowerSteeringFluid,
            @TransmissionFluid,
            @WindScreenWasherFluid,
            @FluidComments,
            @SparkPlugs,
            @FuelFilter,
            @FrontSuspension,
            @FrontSuspensionComments,
            @RearSuspension, 
            @RearSuspensionComments,
            @FrontBrakes,
            @FrontBrakesComments,
            @RearBrakes,
            @RearBrakesComments,
            @Exhaust,
            @ExhaustComments,
            @OilLeaks,
            @OilLeaksComments,
            @CoolantLeaks,
            @CoolantLeaksComments,
            @Other,
            @OtherInspectionComments);
        END
       ELSE 
       BEGIN
        UPDATE Report
        SET
            IsArchive = @IsArchive,
            StartDate = @StartDate,
            EndDate = @EndDate,
            VehicleId = @VehicleId,
            UserId = @UserId,
            AppointmentId = @AppointmentId,
            CustomerId = @CustomerId,
            Date = @Date,
            Odometer = @Odometer,
            RoadTestComments = @RoadTestComments,
            GeneralComments = @GeneralComments,
            StoredFaultCodes = @StoredFaultCodes,
            AirConditioning = @AirConditioning,
            Optics = @Optics,
            Lights = @Lights,
            LightsComments = @LightsComments,
            FrontWiper = @FrontWiper,
            BackWiper = @BackWiper,
            Battery = @Battery,
            BatteryComments = @BatteryComments,
            RHFTyre = @RHFTyre,
            LHFTyre = @LHFTyre,
            RHRTyre = @RHRTyre,
            LHRTyre = @LHRTyre,
            TyresComments = @TyresComments,
            IsNeedAlignment = @IsNeedAlignment,
            AirFilter = @AirFilter,
            CabinFilter = @CabinFilter,
            DriveBelts = @DriveBelts,
            TimingBelts = @TimingBelts,
            Radiator = @Radiator,
            Hoses = @Hoses,
            HosesComment = @HosesComment,
            EngineOil = @EngineOil,
            Coolant = @Coolant,
            BrakeFluid = @BrakeFluid,
            PowerSteeringFluid = @PowerSteeringFluid,
            TransmissionFluid = @TransmissionFluid,
            WindScreenWasherFluid = @WindScreenWasherFluid,
            FluidComments = @FluidComments,
            SparkPlugs = @SparkPlugs,
            FuelFilter = @FuelFilter,
            FrontSuspension = @FrontSuspension,
            FrontSuspensionComments = @FrontSuspensionComments,
            RearSuspension = @RearSuspension,
            RearSuspensionComments = @RearSuspensionComments,
            FrontBrakes = @FrontBrakes,
            FrontBrakesComments = @FrontBrakesComments,
            RearBrakes = @RearBrakes,
            RearBrakesComments = @RearBrakesComments,
            Exhaust = @Exhaust,
            ExhaustComments = @ExhaustComments,
            OilLeaks = @OilLeaks,
            OilLeaksComments = @OilLeaksComments,
            CoolantLeaks = @CoolantLeaks,
            CoolantLeaksComments = @CoolantLeaksComments,
            Other = @Other,
            OtherInspectionComments = @OtherInspectionComments
        WHERE Id = @Id;
    END
END
